package com.orbitguard.report.enums;

/**
 * Defines the supported report types in OrbitGuard AI.
 *
 * <p>
 * Each value represents a specific category of report
 * that can be generated by the Reports module.
 * </p>
 */
public enum ReportType {

    /**
     * Report containing satellite-related information
     * and satellite analytics.
     */
    SATELLITE_ANALYSIS,

    /**
     * Report containing space debris analysis
     * and related information.
     */
    DEBRIS_ANALYSIS,

    /**
     * Report containing collision-risk assessment
     * and risk-related information.
     */
    RISK_ASSESSMENT,

    /**
     * Report containing dashboard-level analytics
     * and system summary information.
     */
    DASHBOARD_ANALYTICS,

    /**
     * Report containing alert-related information,
     * alert history, and alert analytics.
     */
    ALERT_SUMMARY,

    /**
     * AI-enhanced report containing intelligent summaries
     * or explanations generated through the backend AI service.
     */
    AI_ANALYSIS
}