package com.orbitguard.notification.dto.request;

import com.orbitguard.notification.enums.NotificationPriority;
import com.orbitguard.notification.enums.NotificationType;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ===============================================================
 * Create Notification Request DTO
 * ===============================================================
 *
 * Request object used to create a new notification.
 *
 * This DTO contains only the information required from the client.
 * System-managed fields such as notification code, status,
 * timestamps, and soft-delete flag are generated by the backend.
 *
 * Module : Notification Management
 *
 * @author OrbitGuard AI Team
 * @version 1.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateNotificationRequest {

    /**
     * Notification title.
     */
    @NotBlank(message = "Notification title is required.")
    @Size(
            min = 5,
            max = 150,
            message = "Notification title must be between 5 and 150 characters."
    )
    private String title;

    /**
     * Detailed notification message.
     */
    @NotBlank(message = "Notification message is required.")
    @Size(
            min = 10,
            max = 1000,
            message = "Notification message must be between 10 and 1000 characters."
    )
    private String message;

    /**
     * Notification type.
     */
    @NotNull(message = "Notification type is required.")
    private NotificationType type;

    /**
     * Notification priority.
     */
    @NotNull(message = "Notification priority is required.")
    private NotificationPriority priority;

    /**
     * Recipient user identifier.
     */
    @NotBlank(message = "Recipient ID is required.")
    private String recipientId;

    /**
     * Related Alert ID.
     *
     * Optional.
     */
    private String alertId;

    /**
     * Related Collision Risk ID.
     *
     * Optional.
     */
    private String collisionRiskId;

}