package com.orbitguard.alert.entity;

import com.orbitguard.alert.enums.AlertSeverity;
import com.orbitguard.alert.enums.AlertSource;
import com.orbitguard.alert.enums.AlertStatus;
import com.orbitguard.alert.enums.AlertType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * ==============================================================
 * Alert Entity
 * ==============================================================
 *
 * Represents an operational alert generated by
 * OrbitGuard AI.
 *
 * Alerts are created manually or automatically
 * based on collision risk analysis and are used
 * to notify mission operators.
 *
 * Collection : alerts
 *
 * Module : Alert Management
 *
 * @author OrbitGuard AI Team
 * @version 1.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "alerts")
public class Alert {

    /**
     * MongoDB document ID.
     */
    @Id
    private String id;

    /**
     * Business Alert Code.
     *
     * Example:
     * ALT-000001
     */
    @Indexed(unique = true)
    private String alertCode;

    /**
     * Related Collision Risk ID.
     */
    @Indexed
    private String riskId;

    /**
     * Related Satellite ID.
     */
    @Indexed
    private String satelliteId;

    /**
     * Related Space Debris ID.
     */
    @Indexed
    private String debrisId;

    /**
     * Alert title.
     */
    private String title;

    /**
     * Detailed alert message.
     */
    private String message;

    /**
     * Alert severity.
     */
    private AlertSeverity severity;

    /**
     * Current alert status.
     */
    private AlertStatus status;

    /**
     * Source that generated the alert.
     */
    private AlertSource source;

    /**
     * Alert category.
     */
    private AlertType type;

    /**
     * Time when the alert was generated.
     */
    private LocalDateTime generatedAt;

    /**
     * Time when the alert was acknowledged.
     */
    private LocalDateTime acknowledgedAt;

    /**
     * Time when the alert was resolved.
     */
    private LocalDateTime resolvedAt;

    /**
     * Operator remarks.
     */
    private String remarks;

    /**
     * Soft delete flag.
     */
    @Builder.Default
    private Boolean isActive = true;

    /**
     * Record creation timestamp.
     */
    private LocalDateTime createdAt;

    /**
     * Record last update timestamp.
     */
    private LocalDateTime updatedAt;

}