package com.orbitguard.report.util;

import com.orbitguard.report.entity.Report;
import com.orbitguard.report.enums.ReportStatus;
import com.orbitguard.report.enums.ReportType;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class ReportPdfGeneratorTest {

    private final ReportPdfGenerator reportPdfGenerator =
            new ReportPdfGenerator();

    @Test
    void generate_shouldCreateValidPdf() {
        Report report = createValidReport();

        byte[] pdfBytes = reportPdfGenerator.generate(report);

        assertNotNull(pdfBytes);
        assertTrue(pdfBytes.length > 0);

        assertDoesNotThrow(() -> {
            try (PDDocument document =
                         Loader.loadPDF(pdfBytes)) {

                assertEquals(1, document.getNumberOfPages());
            }
        });
    }

    @Test
    void generate_shouldRejectNullReport() {
        assertThrows(
                IllegalArgumentException.class,
                () -> reportPdfGenerator.generate(null)
        );
    }

    @Test
    void generate_shouldHandleLongDescription() {
        String longDescription =
                "OrbitGuard AI report description. ".repeat(100);

        Report report = Report.builder()
                .id("report-id-001")
                .reportCode("RPT-000001")
                .reportType(ReportType.RISK_ASSESSMENT)
                .status(ReportStatus.COMPLETED)
                .title("Long Description Report")
                .description(longDescription)
                .build();

        byte[] pdfBytes = reportPdfGenerator.generate(report);

        assertNotNull(pdfBytes);
        assertTrue(pdfBytes.length > 0);

        assertDoesNotThrow(() -> {
            try (PDDocument document =
                         Loader.loadPDF(pdfBytes)) {

                assertTrue(document.getNumberOfPages() >= 1);
            }
        });
    }

    @Test
    void generate_shouldHandleUnicodeAndSpecialCharacters() {
        Report report = Report.builder()
                .id("report-id-002")
                .reportCode("RPT-000002")
                .reportType(ReportType.AI_ANALYSIS)
                .status(ReportStatus.COMPLETED)
                .title("AI Analysis – OrbitGuard 🚀")
                .description(
                        "Satellite analysis with special characters: "
                                + "© ® ™ € ₹ — • ✓ 漢字"
                )
                .build();

        byte[] pdfBytes = reportPdfGenerator.generate(report);

        assertNotNull(pdfBytes);
        assertTrue(pdfBytes.length > 0);

        assertDoesNotThrow(() -> {
            try (PDDocument document =
                         Loader.loadPDF(pdfBytes)) {

                assertEquals(1, document.getNumberOfPages());
            }
        });
    }

    @Test
    void generate_shouldHandleNullOptionalFields() {
        Report report = Report.builder()
                .id(null)
                .reportCode(null)
                .reportType(null)
                .status(null)
                .title(null)
                .description(null)
                .build();

        byte[] pdfBytes = reportPdfGenerator.generate(report);

        assertNotNull(pdfBytes);
        assertTrue(pdfBytes.length > 0);

        assertDoesNotThrow(() -> {
            try (PDDocument document =
                         Loader.loadPDF(pdfBytes)) {

                assertEquals(1, document.getNumberOfPages());
            }
        });
    }

    private Report createValidReport() {
        return Report.builder()
                .id("report-id-001")
                .reportCode("RPT-000001")
                .reportType(ReportType.RISK_ASSESSMENT)
                .status(ReportStatus.COMPLETED)
                .title("Collision Risk Assessment Report")
                .description(
                        "This report contains collision risk assessment "
                                + "information generated by OrbitGuard AI."
                )
                .build();
    }
}