package com.orbitguard.risk.entity;

import com.orbitguard.risk.enums.AssessmentType;
import com.orbitguard.risk.enums.RiskLevel;
import com.orbitguard.risk.enums.RiskStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "collision_risks")
public class CollisionRisk {

    @Id
    private String id;

    @Indexed(unique = true)
    private String riskCode;

    @Indexed
    private String satelliteId;

    @Indexed
    private String debrisId;

    /**
     * Minimum predicted distance between
     * satellite and debris.
     * Unit : Kilometers
     */
    private Double closestApproachDistanceKm;

    /**
     * Relative velocity between
     * satellite and debris.
     * Unit : Km/s
     */
    private Double relativeVelocityKmPerSec;

    /**
     * Collision probability.
     * Range : 0 - 100
     */
    private Double collisionProbability;

    private RiskLevel riskLevel;

    private RiskStatus status;

    private AssessmentType assessmentType;

    private String remarks;

    /**
     * Recommendation generated by
     * Risk Engine.
     * AI module can overwrite this later.
     */
    private String recommendation;

    @Builder.Default
    private Boolean isActive = true;

    private LocalDateTime assessedAt;

    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    @Builder.Default
    private LocalDateTime updatedAt = LocalDateTime.now();

}