package com.orbitguard.alert.enums;

/**
 * ==============================================================
 * Alert Source
 * ==============================================================
 *
 * Represents the origin of an alert.
 *
 * Knowing the source helps identify how
 * the alert was generated and supports
 * auditing and future integrations.
 *
 * Module : Alert Management
 *
 * @author OrbitGuard AI Team
 * @version 1.0
 */
public enum AlertSource {

    /**
     * Alert generated automatically
     * by the OrbitGuard AI system.
     *
     * Example:
     * High collision probability detected
     * after risk assessment.
     */
    SYSTEM,

    /**
     * Alert generated manually
     * by an administrator or operator.
     */
    MANUAL,

    /**
     * Alert generated by the
     * AI Assistant based on
     * intelligent analysis.
     *
     * Future Feature.
     */
    AI

}