spring.application.name=orbitguard-server

# =====================================================
# SERVER CONFIGURATION
# =====================================================
server.port=8080

# =====================================================
# MONGODB CONFIGURATION
# =====================================================
spring.data.mongodb.uri=mongodb+srv://aashishpatil2144_db_user:Aashish2004@cluster0.hgkxvm7.mongodb.net/orbitguard_db?retryWrites=true&w=majority&appName=Cluster0

# =====================================================
# LOGGING
# =====================================================
logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO

# =====================================================
# JACKSON
# =====================================================
spring.jackson.serialization.indent-output=true

# =====================================================
# DEVTOOLS
# =====================================================
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true