package com.orbitguard.alert.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ==============================================================
 * Create Alert Request
 * ==============================================================
 *
 * Request DTO used to create a new alert.
 *
 * Only business-required information should be supplied
 * by the client. Remaining fields such as:
 *
 * • Alert Code
 * • Severity
 * • Status
 * • Generated Time
 * • Audit Fields
 *
 * are generated by the backend.
 *
 * Module : Alert Management
 *
 * @author OrbitGuard AI Team
 * @version 1.0
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateAlertRequest {

    /**
     * Collision Risk ID.
     */
    @NotBlank(message = "Risk ID is required.")
    private String riskId;

    /**
     * Alert title.
     */
    @NotBlank(message = "Alert title is required.")
    @Size(
            max = 150,
            message = "Alert title must not exceed 150 characters."
    )
    private String title;

    /**
     * Alert message.
     */
    @NotBlank(message = "Alert message is required.")
    @Size(
            max = 1000,
            message = "Alert message must not exceed 1000 characters."
    )
    private String message;

}