package com.orbitguard.notification.enums;

/**
 * Represents the business category of a notification.
 *
 * <p>
 * Notification type identifies the source or purpose of the notification.
 * This enum is designed to be extensible for future integrations such as
 * email, push notifications, and system events.
 * </p>
 *
 * @author OrbitGuard AI
 * @since 1.0
 */
public enum NotificationType {

    /**
     * General system notification.
     */
    SYSTEM,

    /**
     * Alert generated by the Alert Module.
     */
    ALERT,

    /**
     * Collision risk notification generated by the Risk Module.
     */
    COLLISION,

    /**
     * Warning notification requiring user attention.
     */
    WARNING,

    /**
     * General informational notification.
     */
    INFO

}